#!/bin/bash

set -euo pipefail

readonly dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

LOADBALANCER_ADDRESS=192.168.5.30

kubectl config set-cluster kubernetes-the-hard-way \
  --certificate-authority="${dir}/../certificates/ca.crt" \
  --embed-certs=true \
  --server=https://${LOADBALANCER_ADDRESS}:6443 \
  --kubeconfig="${dir}/../config/kube-proxy.kubeconfig"

kubectl config set-credentials system:kube-proxy \
  --client-certificate="${dir}/../certificates/kube-proxy.crt" \
  --client-key="${dir}/../certificates/kube-proxy.key" \
  --embed-certs=true \
  --kubeconfig="${dir}/../config/kube-proxy.kubeconfig"

kubectl config set-context default \
  --cluster=kubernetes-the-hard-way \
  --user=system:kube-proxy \
  --kubeconfig="${dir}/../config/kube-proxy.kubeconfig"

kubectl config use-context default --kubeconfig="${dir}/../config/kube-proxy.kubeconfig"
