#!/bin/bash

set -euo pipefail

readonly dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"



kubectl config set-cluster kubernetes-the-hard-way \
  --certificate-authority="${dir}/../certificates/ca.crt" \
  --embed-certs=true \
  --server=https://127.0.0.1:6443 \
  --kubeconfig="${dir}/../config/kube-controller-manager.kubeconfig"

kubectl config set-credentials system:kube-controller-manager \
  --client-certificate="${dir}/../certificates/kube-controller-manager.crt" \
  --client-key="${dir}/../certificates/kube-controller-manager.key" \
  --embed-certs=true \
  --kubeconfig="${dir}/../config/kube-controller-manager.kubeconfig"

kubectl config set-context default \
  --cluster=kubernetes-the-hard-way \
  --user=system:kube-controller-manager \
  --kubeconfig="${dir}/../config/kube-controller-manager.kubeconfig"

kubectl config use-context default --kubeconfig="${dir}/../config/kube-controller-manager.kubeconfig"
